on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Bundle MoonBit Core
        uses: ./.github/actions/bundle
      - name: Upload MoonBit Core
        uses: actions/upload-artifact@v4
        with:
          name: core.zip
          path: core.zip
