on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Bundle MoonBit core
        uses: ./.github/actions/bundle
      - name: Build Arch Linux packages
        uses: ./.github/actions/package
      - name: Publish
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*.pkg.tar.zst,core.zip'
