on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Bundle MoonBit core
        uses: ./.github/actions/bundle

      - name: Build Arch Linux packages
        uses: ./.github/actions/package

      - name: Update PKGBUILD
        id: pkgbuild
        run: |
          pkgver=$(git diff PKGBUILD | sed -n -E 's/\+pkgver=//p')
          if [ -z "${pkgver}" ]; then
            echo "TAG=x" >> "$GITHUB_OUTPUT"
          else
            echo "TAG=v${pkgver}" >> "$GITHUB_OUTPUT"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add PKGBUILD
            if [ -n "$(git status --porcelain)" ]; then
              git commit -a -m "chore: update PKGBUILD [skip ci]"
              git push origin HEAD:main
            fi
            if [ -z "${pkgver}" ]; then
              echo "No changes to PKGBUILD"
            else
              git tag "v${pkgver}"
              git push origin "v${pkgver}"
            fi
            sed -i -E "s!\"core.zip\"!\"https://github.com/${{ github.repository }}/releases/download/v${pkgver}/core.zip\"!g" PKGBUILD
          fi

      - name: Publish
        if: ${{ steps.pkgbuild.outputs.TAG != 'x' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*.pkg.tar.zst,core.zip'
          tag: ${{ steps.pkgbuild.outputs.TAG }}

      - name: Publish to AUR
        if: ${{ steps.pkgbuild.outputs.TAG != 'x' }}
        uses: KSXGitHub/github-actions-deploy-aur@v2
        with:
          pkgname: moonbit-bin
          pkgbuild: ./PKGBUILD
          assets: ./moon.sh
          commit_username: ${{ github.repository_owner }}
          commit_email: ${{ github.repository_owner }}@users.noreply.github.com
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          commit_message: update
