on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Bundle MoonBit core
        uses: ./.github/actions/bundle

      - name: Update PKGBUILD
        uses: ./.github/actions/update

      - name: Commit version change
        id: pkgbuild
        run: |
          git clone https://aur.archlinux.org/moonbit-bin.git ./.moonbit-bin
          oldver=$(sed -n -E 's/^pkgver=//p' ./.moonbit-bin/PKGBUILD)
          oldrel=$(sed -n -E 's/^pkgrel=//p' ./.moonbit-bin/PKGBUILD)
          pkgver=$(diff -u ./.moonbit-bin/PKGBUILD PKGBUILD | sed -n -E 's/\+pkgver=//p')
          pkgrel=$(diff -u ./.moonbit-bin/PKGBUILD PKGBUILD | sed -n -E 's/\+pkgrel=//p')
          if [ -z "${pkgver}" ] && [ -z "${pkgrel}" ]; then
            echo "TAG=x" >> "$GITHUB_OUTPUT"
            return
          fi
          pkgver="${pkgver:-$oldver}"
          pkgrel="${pkgrel:-$oldrel}"
          tag="v${pkgver}-${pkgrel}"
          echo "TAG=${tag}" >> "$GITHUB_OUTPUT"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add PKGBUILD
          if [ -n "$(git status --porcelain)" ]; then
            git commit -a -m "chore: update PKGBUILD [skip ci]"
            git push origin HEAD:main
          fi
          git tag "${tag}"
          git push origin "${tag}"
          sed -i -E "s!\"core.zip\"!\"https://github.com/${{ github.repository }}/releases/download/${tag}/core.zip\"!g" PKGBUILD

      - name: Build Arch Linux package
        uses: ./.github/actions/package

      - name: Publish
        if: ${{ steps.pkgbuild.outputs.TAG != 'x' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*.pkg.tar.zst,core.zip'
          tag: ${{ steps.pkgbuild.outputs.TAG }}

      - name: Publish to AUR
        if: ${{ steps.pkgbuild.outputs.TAG != 'x' }}
        uses: KSXGitHub/github-actions-deploy-aur@v2
        with:
          pkgname: moonbit-bin
          pkgbuild: ./PKGBUILD
          assets: ./moon.sh
          commit_username: ${{ github.repository_owner }}
          commit_email: ${{ github.repository_owner }}@users.noreply.github.com
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          commit_message: update

      - name: Check
        uses: ./.github/actions/check
