on:
  pull_request:
    branches:
      - main

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Bundle MoonBit core
        uses: ./.github/actions/bundle

      - name: Build Arch Linux package
        uses: ./.github/actions/package
